---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SWF-ForcibleConverter
no_index:
  directory:
    - t
    - inc
requires:
  IO::Compress::Deflate: 0
  IO::File: 0
  IO::Handle: 0
  IO::Uncompress::Inflate: 0
  Test::More: 0.32
version: 0.01
